### ISSUE TITLE
remotehost自己关闭了连接是为什么？

### ISSUE THREAD

**Issue by binogoli** [Alexbeast-CN/Colab_Desktop#1]
/bin/bash: line 0: exec: cloudflared: not found
kex_exchange_identification: Connection closed by remote host

**Comment by Daoming-Chen** [comment]
因为 Colab 资源有限，每隔一定时间（看你的地区，以及你有没有冲会员）就会踢人。当你 remote 连接之后，他默认你没有在操作，所以需要 ColabLive 来延长使用时间，虽然是延长了，但也不会给你非常长的使用时间。
